address_checker/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
    url(r'^$',views.addresses),
    url(r'^split/?$',views.ajax_addresses),
)

microblog/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from . import views
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^sitePass', views.sitePassView, name='sitePass'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^addresses/', include('address_checker.urls', namespace='address_checker')),
    url(r'^', include('section.urls', namespace='section')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
         (r'^static/(?P<path>.*)$', 'django.views.static.serve'),
    )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

section/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name='front'),
    url(r'^contact/$', views.contact_view, name='contact'),
    url(r'^(?P<slug>[\w-]+)/$', views.SectionView.as_view(), name='section'),
)

section/models.py
from django.db import models

class Section(models.Model):
    """Section Page"""
    title = models.CharField(max_length=255)
    sort_key = models.IntegerField(default=0)
    slug = models.SlugField(max_length=255, blank=True)
    blurb = models.TextField(blank=True)
    nav = models.BooleanField()
    
    class Meta:
        ordering = ['sort_key', 'title']
    
    def __unicode__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Section, self).save(*args, **kwargs)


class Slice(models.Model):
    """Container for Grid blocks"""
    section = models.ForeignKey(Section)
    sort_key = models.IntegerField(default=0)
    title = models.CharField(max_length=225, blank=True)
    
    class Meta:
        ordering = ['sort_key']
    
    def __unicode__(self):
        return '{0}: {1} ({2})'.format(self.section, self.sort_key, self.title)
        

class Grid(models.Model):
    """"define grid-size choices"""
    GRID_CHOICES = (
        ('full', 'Full'),
        ('half', 'Half'),
        ('third', 'Third'),
        ('two-thirds','Two-Thirds'),
        ('quarter', 'Quarter'),
    )
    
    slice = models.ForeignKey(Slice)
    size = models.CharField(max_length=10, choices=GRID_CHOICES)
    sort_key = models.IntegerField(default=0)
    header = models.CharField(max_length=255, blank=True)
    # holds content, or image title text
    content = models.TextField(blank=True)
    # if anything, it's code
    language = models.CharField(max_length=16, blank=True)
    # if anything, it's an img
    img = models.FileField(upload_to='section/img', blank=True)
    
    class Meta:
        ordering = ['slice__section__title', 'slice__sort_key', 'sort_key']
    
    def __unicode__(self):
        return '{0}-{1}'.format(self.slice, self.sort_key)


class Link(models.Model):
    grid = models.ForeignKey(Grid)
    # the text to display as a link
    display = models.CharField(max_length=255)
    # a contact me link
    contact_link = models.BooleanField()
    # a link to another section
    section_link = models.ForeignKey(Section, null=True, blank=True)
    # a url link
    other_link = models.CharField(max_length=225, blank=True)
    # an uploaded file
    file_link = models.FileField(upload_to='section/bin', blank=True)

    class Meta:
        ordering = ['grid__slice__section__title', 'grid__slice__sort_key',
                    'grid__sort_key', 'display']
    
    def __unicode__(self):
        return '{0}> {1}'.format(self.grid, self.display)

address_checker/forms.py
from django import forms

class AddressForm(forms.Form):
    address1 = forms.CharField()
    address2 = forms.CharField(required=False)
    has_attn = forms.BooleanField(required=False)

section/forms.py
from django import forms

class ContactEmail(forms.Form):
    emailfrom = forms.EmailField()
    email = forms.CharField()

address_checker/views.py
from django.shortcuts import render
from forms import AddressForm
import SplitAddress
from section.views import add_header_footer
from django.http import HttpResponse
import json

def addresses(request):
    context={}
    context = add_header_footer(context)
    return render(request,'address_checker/splitter.html',context)

def ajax_addresses(request):
    split={}
    
    if request.is_ajax():
        form=AddressForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            sr = SplitAddress.Splitter_Regex()
            split = SplitAddress.Splitter(sr,cd['address1'],cd['address2'],cd['has_attn']).addys
            #return render(request,'address_checker/splitter.html',context)
            return HttpResponse(json.dumps(split), content_type="application/json")

microblog/views.py
from django.views.generic import TemplateView
from django.shortcuts import render

class HomepageView(TemplateView):
    template_name = 'index.html'

def sitePassView(request, *args, **kwargs):
    template_name = "sitePass.html"
    return render(request, template_name)

section/views.py
from .models import Section, Slice, Grid, Link
from django.views.generic import DetailView, ListView
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
from forms import ContactEmail
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
import json, smtplib

def add_header_footer(context):
    '''add the header and footer to the context'''
    # header
    context['nav_list'] = Section.objects.exclude(slug='footer').order_by('sort_key').filter(nav=True)
    print('nav list:')
    print(context['nav_list'])
    # footer
    footer_section = Section.objects.filter(slug='footer')
    context['footer_slice'] = Slice.objects.filter(section=footer_section[0].id)[0]
    context['footer_grid_list'] = Grid.objects.filter(slice=context['footer_slice'].id)
    context['footer_link_list']=[]
    for grid in context['footer_grid_list']:
        grid_links = Link.objects.filter(grid=grid.id)
        context['footer_link_list'] += grid_links
    
    return context

def get_max(grid_list):
    max = 0
    max_id = 0
    for grid in grid_list:
        if grid.sort_key > max:
            max = grid.sort_key
            max_id = grid.id
    return max_id

class SectionView(DetailView):
    model = Section
    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(SectionView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the sections
        context['slice_list'] = Slice.objects.filter(section=context['section'].id)
        context['grid_list'] = []
        # filter the grids and add them
        for slice in context['slice_list']:
            # set the type
            slice.type = (slice.sort_key + 1) % 2
            # get the grids
            slice_grids = Grid.objects.filter(slice=slice.id)
            slice.max = get_max(slice_grids)
            context['grid_list'] += slice_grids
            # links
            context['link_list']=[]
            for grid in context['grid_list']:
                grid_links = Link.objects.filter(grid=grid.id)
                context['link_list'] += grid_links
        
        context = add_header_footer(context)
        
        return context


class HomeView(ListView):
    model = Section
    
    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context = add_header_footer(context)
        
        return context


@csrf_exempt
def contact_view(request):
  if request.is_ajax():
    form=ContactEmail(request.POST)
    if form.is_valid():
      cd = form.cleaned_data
      
      try:
        print(settings.CONTACT_EMAIL_TO)
        send_mail('Contact Me Email',cd['email'],cd['emailfrom'],[settings.CONTACT_EMAIL_TO],fail_silently=False)
      except Exception as e:
        response = json.dumps({'sent':False,'message':'There was a server error: {}'.format(e)})
      else:
        response = json.dumps({'sent':True,'message':''})
      
      return HttpResponse(response, content_type="application/json")

address_checker/templates/address_checker/splitter.html
{% extends "section/base.html" %}
{% load jstemplate %}

{% block page_title %}Normalized Address Splitter | {% endblock %}
{% block meta_description %}
This page takes a two-field address and splits it into a normalized seven-field address
{% endblock %}

{% block links %}
<link rel='stylesheet' href='{{ STATIC_URL }}address_checker/address_checker.css' type='text/css'>
<script type='text/javascript' src='{{ STATIC_URL }}lib/jquery-2.0.3.min.js'></script>
<script type='text/javascript' src='{{ STATIC_URL }}lib/mustache.js'></script>
<script type='text/javascript' src='{{ STATIC_URL }}address_checker/address_checker.js'></script>
{% mustachejs "address" %}
{% endblock %}


{% block content %}
<div class='nav-bar'><nav>
    {% for nav in nav_list %}
    {% ifequal nav.id section.id %}
    <a class='menu-a menu-curr' href="{% url 'section:section' nav.slug %}">{{ nav.title }}</a>
    {% else %}
    <a class='menu-a' href="{% url 'section:section' nav.slug %}">{{ nav.title }}</a>
    {% endifequal %}
    {% endfor %}
</nav></div>

<div class='slice-back'></div><div class='foot-back'></div>
<div class='slice slice-0'><div class='slice-container'>
<div class='grid grid-full'><div class='grid-container grid-cont-mid'>
<div class='slice-head'>Split an Address</div>
  <p>
    This is a sample page that shows off some of my python and ajax skills.
  </p>
  <p>
    It is hooked up to a python address splitter function, which uses regular expressions to break a two-field address into a seven-field one.
    It's mostly useful when converting an address database from a limited two-line
    format to a modern, normalized format, where each piece of the address has its own field.
  </p>
  <p>
    I've used ajax techniques to query the python script without refreshing the page, and then add another set of fields to add more data into.
  </p>
  <br/>
  <p>
    Since addresses come in a lot of formats, a two-line database can have a lot of weird formats 
    crammed into those lines. This attempts to parse all of that. 
  </p>
  <p>
    This page is just an example - put in two address lines, and it'll spit out a nicely parsed address, and give you the space to try another one.
    But if you just wanted to split a single address, you could do that yourself. The real beauty of this
    sort of function in when you have thousands of records to clean. Check back soon, and you'll be able to upload
    a text file of addresses and get a download of them all split up.
  </p>
</div></div>
</div></div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends "_layouts/base.html" %}

{% block page_title %}Blog posts | {% endblock %}

{% block page_content %}
<h2>Blog Posts</h2>
<ul>
    {% for post in post_list %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% empty %}
    <li>Sorry, no posts yet. Check back soon!</li>
    {% endfor %}
</ul>
{% endblock %}

microblog/templates/sitePass.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>sitePass: a unique password generator | When there's a Will</title>
    <meta name="description" content='sitePass generates passwords based on a site url and a password.'/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="initial-scale=1.0, width=device-width" />
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Raleway:200,700' type='text/css'>
    <link rel='stylesheet' href='{{ STATIC_URL }}sitePass/sitePass.css'/>
    <script type='text/javascript' src='{{ STATIC_URL }}sitePass/sha256.js'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}sitePass/seedrandom.js'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}sitePass/sitePass.js'></script>
    <link rel="shortcut icon" type="image/ico"  href="{{ STATIC_URL }}sitePass/favicon.ico"/>
    
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    
      ga('create', 'UA-46052002-1', 'whentheresawill.net');
      ga('send', 'pageview');
    
    </script>
</head>
<body>
    <div class='container'>
		<h2>sitePass:</h2>
		<h3>Generate a password for each of your websites!</h3>
        <form>
			<div>
            <p id='lab_site'>Website:</p><p id='lab_iteration'>Iteration:</p> 
			<input type='text' id='txt_site' value='example.com' placeholder='example.com'>
			<input type='number' id='num_iteration' value=1 placeholder='#'>
			</div>
            
            <p id='lab_password'>Your password:</p> <input type='password' id='txt_password' placeholder='Password' autofocus='autofocus'>
            
            <input type='button' id='btn_generate' value="Generate Password"/>
            
            <p>New password:</p> <input type='text' id='txt_new_pass'>
            
            <a class='link' target='_blank' href='http://whentheresawill.net/about-sitePass'><p>Find out more</p></a>
        </form>
    </div>
</body>
</html>

section/templates/section/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block page_title %}{% endblock %}When there's a Will</title>
    <meta name="description" content='{% block meta_description %}{% endblock %}' />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="initial-scale=1.0, width=device-width" />
    <link rel="stylesheet" href='{{ STATIC_URL }}section/css/modern.css'/>
    <link href='https://fonts.googleapis.com/css?family=Oxygen:400,700|Bevan' rel='stylesheet' type='text/css' />
    {% block links %}
    {% endblock %}
    
    <link rel="shortcut icon" type="image/ico"  href="/static/favicon.ico"/>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script language="javascript" type="text/javascript" src="{{ STATIC_URL }}section/js/jquery.willpop.min.js"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    
      ga('create', 'UA-46052002-1', 'whentheresawill.net');
      ga('send', 'pageview');
    
    </script>
</head>
<body><div class=container>
    <div class='top-head'>
        <div class='title-container'><a href="{% url 'section:front' %}"><h1>When there's a Will...</h1></a></div>
    </div>
	{% block content %}
  {% endblock %}
	<div class='footer-blocker'></div>
	{% block footer-type %}<footer>{% endblock %}
	    {% for grid in footer_grid_list %}
        {% ifequal grid.slice.id footer_slice.id %}
        <div class='grid grid-{{ grid.size }}'><div class='grid-container grid-cont-mid'><p>
          {% if grid.content %}
          <span class='no-link'>{{ grid.content|safe }}<br/></span>
          {% endif %}
        {% for link in footer_link_list %}
        {% ifequal link.grid.id grid.id %}
        {% if link.contact_link %}
          <span id="contact">{{ link.display }}</span><br/>
        {% else %}
          {% if link.section_link %}
          <a href="{% url 'section:section' link.section_link.slug %}">
          {% elif link.other_link %}
          <a href="{{ link.other_link }}">
          {% elif link.file_link %}
          <a href="{{ link.file_link.url }}">
          {% else %}
          <a>
          {% endif %}
          {{ link.display }}</a><br/>
        {% endif %}
        {% endifequal %}
        {% endfor %}
        </p></div></div>
        {% endifequal %}
        {% endfor %}
	</footer>
</div>
<script>
  $('#contact').addContactPop({
    emailUrl: '{% url "section:contact" %}',
    emailMsg: 'Send me an email!',
    socialMsg: 'Find me on social media:',
    socialUrls: {
      github: 'http://github.com/whenther',
      linkedin: 'https://www.linkedin.com/in/willlw',
      twitter: 'http://twitter.com/Will_LW'
    },
    socialDir: '{{ STATIC_URL }}section/img/social_icons/'
  });
</script>
</body>
</html>

section/templates/section/section_detail.html
{% extends "section/base.html" %}

{% block page_title %}{{ section.title }} | {% endblock %}
{% block meta_description %}{{ section.blurb }}{% endblock %}

{% block links %}
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}section/css/shCoreEclipse.css"/>
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}section/css/shThemeEclipse.css"/>
    <script type="text/javascript" src="{{ STATIC_URL }}section/js/shCore.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}section/js/shAutoloader.js"></script>
{% endblock %}

{% block content %}
<div class='nav-bar'><nav>
    {% for nav in nav_list %}
    {% ifequal nav.id section.id %}
    <a class='menu-a menu-curr' href="{% url 'section:section' nav.slug %}">{{ nav.title }}</a>
    {% else %}
    <a class='menu-a' href="{% url 'section:section' nav.slug %}">{{ nav.title }}</a>
    {% endifequal %}
    {% endfor %}
</nav></div>
<div class='slice-back'></div><div class='foot-back'></div>
{% for slice in slice_list %}
{% ifequal slice_list.count 1 %}
<div class='slice slice-0'><div class='slice-container'>
{% else %}
<div class='slice slice-{{ slice.type }}'><div class='slice-container'>
{% endifequal %}
    {% if slice.title %}
    <div class='slice-head'>{{ slice.title|safe }}</div>
    {% endif %}
    {% for grid in grid_list %}
    {% ifequal grid.slice.id slice.id %}
    <div class='grid grid-{{ grid.size }}'>
    {% if grid.sort_key == 1 %}
    <div class='grid-container grid-cont-left'>
    {% elif grid.sort_key == slice.max %}
    <div class='grid-container grid-cont-right'>
    {% else %}
    <div class='grid-container grid-cont-mid'>
    {% endif %}
        <h3>{{ grid.header|safe }}</h3>
        {% if grid.img %}
        <img class=grid-img src='{{ grid.img.url }}' title='{{ grid.content }}'/>
        {% elif grid.language %}
        <pre class='brush: {{ grid.language }}'>{{ grid.content }}</pre>
        {% else %}
        {{ grid.content|safe|linebreaks }}
        {% for link in link_list %}
        {% ifequal link.grid.id grid.id %}
        {% if link.section_link %}
        <a href="{% url 'section:section' link.section_link.slug %}">
        {% elif link.other_link %}
        <a href="{{ link.other_link }}">
        {% elif link.file_link %}
        <a href="{{ link.file_link.url }}">
        {% else %}
        <a>
        {% endif %}
        {{ link.display }}</a><br/>
        {% endifequal %}
        {% endfor %}
        {% endif %}
    </div></div>
    {% endifequal %}
    {% endfor %}
</div></div>
{% empty %}
<div class='slice slice-0'><div class='grid grid-full'><div class='grid-container'>
<h2>This section is still in development.</h2>
</div></div></div>
{% endfor %}

<script type="text/javascript">
    SyntaxHighlighter.autoloader(
    'py python                {{ STATIC_URL }}section/js/shBrushPython.js',
    'js jscript javascript    {{ STATIC_URL }}section/js/shBrushJScript.js',
    'sql mysql                {{ STATIC_URL }}section/js/shBrushSql.js',
    'vb vbnet                 {{ STATIC_URL }}section/js/shBrushVb.js'
    );
    SyntaxHighlighter.all();
</script>
    
{% endblock %}

section/templates/section/section_list.html
{% extends "section/base.html" %}
    
{% block content %}
    <div class='slice slice-front'><div class='slice-container'>
        {% for nav in nav_list %}
        <div class='grid grid-quarter'><div class='grid-container'>
        <a href="{% url 'section:section' nav.slug %}">{{ nav.title }}</a>
        <p>{{ nav.blurb }}</p>
        </div></div>
        {% endfor %}
    </div></div>
{% endblock %}

{% block footer-type %}<footer class='front-footer'>{% endblock %}